name: 'Format and Validate'

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  fmt:
    name: 'cargo fmt'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Setup Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    - uses: mbrobbel/rustfmt-check@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
  validate:
    name: 'Validate fly config'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Setup fly CLI
      uses: superfly/flyctl-actions/setup-flyctl@master
    - name: Validate fly config
      id: validate
      run: flyctl config validate
